feat: allow configuration of repoUrl and revision (#59)
argoproj/notifications-engine pull request #103
Opened 2022-08-31 19:47 UTC by tback

First PR here. Do you mind to let me know what's required to move this forward?

Signed-off-by: Till Backhaus <till@legalos.io>

2022-10-15 19:13 UTC, jkroepke commented
How to define a custom revision? Define a static revision as annotation may a bit pointless.

2022-11-28 21:23 UTC, pasha-codefresh requested changes

2022-11-28 21:23 UTC, pasha-codefresh commented on pkg/services/github.go
>  type GitHubNotification struct {
If you remove "Status" field it can cause breaking changes for existing customers, why do you need to change it?

2022-12-05 22:49 UTC, nan-yu commented on pkg/services/github.go
> +		repoURLtemplate = g.RepoURL
I think `g.RepoURL` refers to the actual git repo URL (e.g. `https://github.com/argoproj-labs/argocd-notifications.git`), while `repoURLtemplate` refers to the API field path (e.g. `{{.app.spec.source.repoURL}}`).
I would suggest using two fields to separate them as #115.

2022-12-06 12:45 UTC, pasha-codefresh commented
Solved already in https://github.com/argoproj/notifications-engine/pull/115  , Thank you for effort that you did!

2022-12-06 12:45 UTC, closed without merging