fix: oncePer condition only checked when `when` condition is true (#71)
argoproj/notifications-engine pull request #208
Opened 2023-08-11 15:06 UTC by lol3909

This change makes it that the oncePer condition only gets check if the `when` condition is true.
fixes #71

2023-09-07 20:38 UTC, mubarak-j commented
@pasha-codefresh would you be able to review this PR?

2023-10-02 17:34 UTC, lol3909 commented
Hi, any news on this? :) @mubarak-j or @pasha-codefresh

2023-10-02 18:01 UTC, mubarak-j commented
I pinged the maintainers on Slack https://cloud-native.slack.com/archives/C01TSERG0KZ/p1696269136126209
I'm just an end-user that hoping this long-standing annoying bug gets resolved, pretty sure will help save in log costs 💸 😄

2023-10-19 08:56 UTC, pasha-codefresh requested changes

2023-10-19 08:56 UTC, pasha-codefresh commented on pkg/triggers/service.go
> +			whenResult = false
whenResult can be false by default, so you will not need write this line

2023-10-19 08:56 UTC, pasha-codefresh commented on pkg/triggers/service.go
> +		log.Debug("This is the version with the whenResult variable")
i think this log is redundant

2023-10-19 08:57 UTC, pasha-codefresh commented
Hey @lol3909 , added few small comments

2023-10-19 14:26 UTC, merged