feat: support for Google Chat
argoproj/notifications-engine pull request #45
Opened 2021-09-16 02:57 UTC by francilioaraujo

Google chat uses json for its webhook input format. Even though there's already a webhook service, a customized one can be more pleasant to use.

2021-09-16 03:01 UTC, francilioaraujo commented
I will add documentation

2021-09-27 10:03 UTC, ryota-sakamoto requested changes
Thank you for contributing.

2021-09-27 10:03 UTC, ryota-sakamoto commented on docs/services/googlechat.md
> +  name: argocd-notifications-cm
Would you replace `argocd-notifications-cm` to `<config-map-name>`?

2021-09-27 10:03 UTC, ryota-sakamoto commented on pkg/cmd/context.go
> +		data, err = ioutil.ReadFile(filePath)
Why have you changed this file?

2021-09-27 10:03 UTC, ryota-sakamoto commented on docs/services/googlechat.md
> +    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: channelName
I guess the correct value is spaceName, right?

2021-09-27 10:03 UTC, ryota-sakamoto commented on pkg/services/googlechat.go
> +		return fmt.Errorf("cannot create message: %s", err)
cannot send message

2021-09-27 10:03 UTC, ryota-sakamoto commented on docs/services/googlechat.md
> +# Google Chat
Would you add the link of this doc to overview.md?

2021-09-27 10:03 UTC, ryota-sakamoto commented on pkg/services/googlechat.go
> +		return fmt.Errorf("cannot create message: %s", err)
Would you wrap the error using `%w` instead of `%s`?

2021-09-27 12:45 UTC, francilioaraujo commented on pkg/cmd/context.go
> +		data, err = ioutil.ReadFile(filePath)
With `c.configMapPath` the secret is read from the same file with the ConfigMap. The parameter `filePath` is the path from `--secret`, so I thought this path should be used here. But I can reverse this change if you will

2021-09-27 12:45 UTC, francilioaraujo commented on docs/services/googlechat.md
> +    notifications.argoproj.io/subscribe.on-sync-succeeded.googlechat: channelName
Indeed, it is

2021-09-27 12:50 UTC, francilioaraujo commented on docs/services/googlechat.md
> +  name: argocd-notifications-cm
Fixed

2021-09-30 17:46 UTC, francilioaraujo commented on pkg/cmd/context.go
> +		data, err = ioutil.ReadFile(filePath)
@ryota-sakamoto , what do you think about this? Should I revert these changes?

2021-10-18 06:18 UTC, alexmt commented on pkg/cmd/context.go
> +		data, err = ioutil.ReadFile(filePath)
Looks like this is valid fix. Thanks for catching it @francilioaraujo .  I'm fine to keep the change

2021-11-12 17:37 UTC, alexmt commented
All commits of this PR have been merged to master.

2021-11-12 17:37 UTC, closed without merging