Support send message to telegram as markdown
argoproj/notifications-engine pull request #54
Opened 2021-11-16 07:36 UTC by vietanhduong

Send a message to Telegram as Markdown

2021-11-16 07:56 UTC, vietanhduong commented
@ryota-sakamoto, Would you review this PR please?

2021-11-16 19:15 UTC, pasha-codefresh requested changes

2021-11-16 19:15 UTC, pasha-codefresh commented on pkg/services/telegram.go
> +
Please fix linter issues

2021-11-17 06:30 UTC, pasha-codefresh approved these changes

2021-11-17 06:48 UTC, alexmt approved these changes

2021-11-17 07:06 UTC, merged

2021-11-17 09:10 UTC, pasha-codefresh commented
Thank you @vietanhduong !

2024-06-14 16:50 UTC, ajax-bychenok-y commented
Can somebody share an example how to use message in markdown through argo-notification? I can't manage to do so.