docs: Add documentation for RocketChat
argoproj/notifications-engine pull request #6
Opened 2021-04-23 05:53 UTC by sergeyshevch

Signed-off-by: Sergey Shevchenko <sergey.shevchenko@dteam.dev>

2021-04-23 15:33 UTC, ryota-sakamoto requested changes
please add to `Service Types`.
https://github.com/argoproj/notifications-engine/blob/aa774e755de808339b9790c995ce8fd14120f003/docs/services/overview.md#L39-L49

2021-04-23 15:33 UTC, ryota-sakamoto commented on docs/services/rocketchat.md
> +## Configuration
Would you add Parameters section like as follows, please?

https://github.com/argoproj/notifications-engine/blob/aa774e755de808339b9790c995ce8fd14120f003/docs/services/github.md#L3-L11

2021-04-23 15:33 UTC, ryota-sakamoto commented on docs/services/rocketchat.md
> +    alias: <alias>          # Username alias
Would you define minimum sample, please? and move to Parameters section.

2021-04-23 15:33 UTC, ryota-sakamoto commented on docs/services/rocketchat.md
> +<!-- TODO: @sergeyshevch Need to add screenshot with RocketChat attachments -->
please paste screenshot.

2021-04-23 15:33 UTC, ryota-sakamoto commented on docs/services/rocketchat.md
> +9. Create a subscription for your Slack integration:
Is it `Rocket.Chat`?

2021-05-22 19:12 UTC, alexmt commented
Closing since https://github.com/argoproj/notifications-engine/pull/25 has the same changes

2021-05-22 19:12 UTC, closed without merging