feat: PagerDuty Integration
argoproj/notifications-engine pull request #79
Opened 2022-03-09 11:31 UTC by RaviHari

Signed-off-by: Ravi Hari <ravireliable@gmail.com>
Fixes: https://github.com/argoproj/notifications-engine/issues/78

2022-03-25 18:32 UTC, harikrongali commented
@RaviHari Thanks for refactoring to add serviceId as subscription

2022-04-06 17:58 UTC, pasha-codefresh requested changes
Really great job, just few small comments

2022-04-06 17:58 UTC, pasha-codefresh commented on pkg/services/pagerduty.go
> +	Title, err := texttemplate.New(name).Funcs(f).Parse(p.Title)
please change to title

2022-04-06 17:58 UTC, pasha-codefresh commented on pkg/services/pagerduty.go
> +	Urgency, err := texttemplate.New(name).Funcs(f).Parse(p.Urgency)
urgency

2022-04-06 17:58 UTC, pasha-codefresh commented on pkg/services/pagerduty.go
> +	PriorityID, err := texttemplate.New(name).Funcs(f).Parse(p.PriorityID)
priorityId

2022-04-06 17:58 UTC, pasha-codefresh commented on docs/services/pagerduty.md
> +* `pagerduty-token` - the pagerduty auth token
wdyt about rename it to pagerdutyToken to be consiste with other params

2022-04-06 17:58 UTC, pasha-codefresh commented on pkg/services/services.go
> +	_ "github.com/golang/mock/mockgen/model"
why you need this dependency here?

2022-04-06 17:58 UTC, pasha-codefresh commented on pkg/services/pagerduty.go
> +	Title := notification.Pagerduty.Title
same here with varibles

2022-04-07 12:03 UTC, pasha-codefresh approved these changes
Great job, thank you!

2022-04-07 12:03 UTC, merged