feat(services): add NewRelic service
argoproj/notifications-engine pull request #92
Opened 2022-05-21 06:20 UTC by saviogl

Hi folks,

My company is in the process of rolling out New Relic internally and I saw an opportunity for adding a new notification service for it to integrate with its [Deployment Marker](https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/record-monitor-deployments/) functionality.

Not sure if the contributing process involving opening up an issue first, etc, so just let me know if changes are need to be made.

Also, pretty new to the Argoproj codebase, so let me know if I missed any aspect of adding a new notification service, or if there are any other considerations/suggestions. Haven't tested e2e, not sure the best way of doing so within this codebase or integrated with the ArgoCD one.

2022-05-26 20:08 UTC, saviogl commented
@alexmt Just making sure I'm following the right approach here

2022-06-01 23:06 UTC, saviogl commented
@ryota-sakamoto Maybe you can shed some light on the contributing process here?

2022-11-26 21:47 UTC, pasha-codefresh commented
Hey @saviogl , i am going to review it

2022-11-27 00:48 UTC, saviogl commented
@pasha-codefresh Thanks for getting back to me, I wasn't sure if this repository was still active, or how I could follow up on the contribution process. I had left a few messages back in the day on Slack, but to no avail.

Glad that we are coming around to it, it's been a while so I might need a refresher myself. I ended up using Webhooks Notifications Service to setup the foundation for the company that I worked for but it would be great to have this abstraction as a supported service.

Let me know if you have any questions...

On another note, If I wanted to get more involved with the argo project, where would be the best place to start?

2022-11-27 09:20 UTC, pasha-codefresh commented
ArgoCD is good candidate, but notification is also part of it, i would say that notification also great place for beginning. 

About PR, the code itself looks good to me, I just want run a manual test on it today, and after we can merge

2022-11-27 16:59 UTC, pasha-codefresh requested changes

2022-11-27 16:59 UTC, pasha-codefresh commented on docs/services/newrelic.md
> +  service.mattermost: |
Please change it to newrelic

2022-11-27 17:30 UTC, pasha-codefresh requested changes

2022-11-27 17:30 UTC, pasha-codefresh commented on docs/services/newrelic.md
> +## Templates
Probably also add description that cover it. ? 

```
commitAuthorTemplate := n.User
	if commitAuthorTemplate == "" {
		commitAuthorTemplate = "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Author}}"
	}
```

You can hardcode user if needed

2022-11-27 17:30 UTC, pasha-codefresh commented on docs/services/newrelic.md
> +    changelog: "{{(call .repo.GetCommitMetadata .app.status.sync.revision).Message}}"
If you not define user you take it from metadata, probably same should be done for changelog ?

2022-11-27 17:34 UTC, pasha-codefresh commented
@saviogl i got it working, great job, lets just fix small issues in documentation 
![Снимок экрана 2022-11-27 в 19 34 01](https://user-images.githubusercontent.com/39732895/204150831-5b408004-6f3b-4992-82c5-b288da826b72.png)

2022-11-29 19:12 UTC, pasha-codefresh commented
Hey @saviogl , do you need some help with solve comments that i provided?

2022-11-29 19:34 UTC, saviogl commented
Hi @pasha-codefresh, I'll be looking at this today, and I'll let you know if I come across any questions? Are you in CNCF Slack workspace?

2022-11-29 22:08 UTC, pasha-codefresh commented
Yep @saviogl , messaged you in slack

2022-11-30 09:34 UTC, pasha-codefresh approved these changes

2022-11-30 09:34 UTC, merged

2022-11-30 09:34 UTC, pasha-codefresh commented
Great job, thank you!